### ISSUE TITLE
Information on working ROS Noetic Setup with PyQt5

### ISSUE THREAD

**Issue by Olimoyo** [IFL-CAMP/easy_handeye#101]
Hi,

I was looking for some advice from someone who was able to get this package working with ROS Noetic.

The main issue I'm having is  indirectly related to this package and has to do with `PyQt5`. I'm currently using the following versions:
```
PyQt5                         5.15.6
PyQt5-Qt5                     5.15.2
PyQt5-sip                     12.10.1
```
When I run the following command `rosrun rqt_gui rqt_gui`, I get the following error:
```
ValueError: PyCapsule_GetPointer called with incorrect name
```

The GUI used by this package also leads to this error since I'm assuming it uses a similar call at some point.

If someone was able to get this to work with ROS Noetic, what version or setup of PyQt5 did you use? 

Thanks!
Oliver

**Comment by dongyi-ur** [comment]
I have the same problem.
And for my case, it mainly because the conda conflicts with the calibration package.
I creat a new workspace and run it in my computer's env (not Virtual Environment) successfully.

**Comment by Olimoyo** [comment]
Would it be possible for you to type `pip list` and to see what version's of PyQT worked for you on your computer's env?

**Comment by dongyi-ur** [comment]
dongyi@dongyi-ur:~$ pip show PyQt5
Name: PyQt5
Version: 5.14.1
Summary: None
Home-page: None
Author: None
Author-email: None
License: None
Location: /usr/lib/python3/dist-packages
Requires: 
Required-by:

**Comment by dongyi-ur** [comment]
![Screenshot from 2022-06-13 23-48-59](https://user-images.githubusercontent.com/66419321/173471674-cb95c324-1684-4c77-a3ee-127e13eae500.png)

**Comment by dongyi-ur** [comment]
![Screenshot from 2022-06-14 09-02-27](https://user-images.githubusercontent.com/66419321/173471776-f615e84b-d38f-4cf4-88d7-acb1f2288cd2.png)

**Comment by Olimoyo** [comment]
Thank you! I'll give it a try in the next few days.

**Comment by marcoesposito1988** [comment]
This seems to be a conflict with conda. Please reopen the issue if this occurs with a clean installation of 20.04/noetic.
