### ISSUE TITLE
meet some fetal trouble

### ISSUE THREAD

**Issue by wangqingyu985** [IFL-CAMP/easy_handeye#115]
i am using franka and realsense D435, eye on base.
but there are some fetal problems.
there are not menu on the interface, and the rviz seems to have problem
![1](https://user-images.githubusercontent.com/37773801/197329920-424fb62a-ef7b-496d-b41d-c43a8de47b0d.png)
![2](https://user-images.githubusercontent.com/37773801/197329924-6e50f0de-9f72-4c86-a4b2-acdbb53d1a7b.png)

**Comment by wangqingyu985** [comment]
who can help me

**Comment by Akumar201** [comment]
Hello @wangqingyu985 as far as I can see, have  you launched  move_group.launch ? Please visit **https://answers.ros.org/question/258298/robot-semantic-description-not-found/** for further information. Feel free to ask a followup question if you require any further assistance.

**Comment by wangqingyu985** [comment]
Finally, I have solved the problem, thank you.

**Comment by Akumar201** [comment]
Please close the issue if it has been resolved.
