### ISSUE TITLE
How to callibrate raspberry pi camera with easy handeye.

### ISSUE THREAD

**Issue by Akumar201** [IFL-CAMP/easy_handeye#120]
Hi, I would like to know how can I calibrate raspberry pi camera using easy handeye calibration. I am using https://www.raspberrypi.com/products/pi-noir-camera-v2/ camera .

**Comment by marcoesposito1988** [comment]
Hi @Akumar201,

you can probably try using [raspicam_node](https://github.com/UbiquityRobotics/raspicam_node) and follow the documentation of this repo to track a charuco marker
