### ISSUE TITLE
pip2 + transforms3d ？？？

### ISSUE THREAD

**Issue by JerryHAO1** [IFL-CAMP/easy_handeye#126]
I use :  rosdep install -iyr --from-paths src

but:
ERROR: the following rosdeps failed to install
  pip: command [sudo -H pip2 install -U transforms3d] failed
  pip: Failed to detect successful installation of [transforms3d]

**Comment by marcoesposito1988** [comment]
Hi @JerryHAO1,

is this melodic? in this case you may need to use an earlier version
