### ISSUE TITLE
No transform from [base] to frame [world]

### ISSUE THREAD

**Issue by MARHEM602** [IFL-CAMP/easy_handeye#128]
Hello, I am trying to calibrate my fanuc robot (Cr7ial) with a kinect v1 camera.

Here is my program:

<?xml version="1.0" ?>
<launch>

    <arg name="namespace_prefix" default="fanuc_kinect_handeyecalibration" />
    <arg name="marker_size" doc="Size of the ArUco marker used, in meters" />
    <arg name="marker_id" doc="The ID of the ArUco marker used" />
    <arg name="reference_frame" value="camera_link"/>

   

    <include file="$(find openni_launch)/launch/openni.launch" >

        <arg name="depth_registration" value="true" />

    </include>

   

   
    <node name="aruco_single" pkg="aruco_ros" type="single">
        <remap from="/camera_info" to="/openni/qhd/camera_info" />
        <remap from="/image" to="/openni/qhd/image_color_rect" />
        <param name="image_is_rectified" value="false"/>
        <param name="marker_size"        value="0.08"/>
        <param name="marker_id"          value="26"/>
        <param name="reference_frame"    value="camera_link"/>
        <param name="camera_frame"       value="camera_rgb_optical_frame"/>
        <param name="marker_frame"       value="camera_marker" />
    </node>

   

    <include file="$(find fanuc_cr7ial_moveit_config)/launch/moveit_planning_execution.launch">

        <arg name="sim" value="false"/>
        <arg name="robot_ip" value="192.168.0.9" doc="Adresse IP du robot Fanuc CR-7iAL" />

    </include>

   
    <include file="$(find easy_handeye)/launch/calibrate.launch" >
        <arg name="namespace_prefix" value="$(arg namespace_prefix)" />
        <arg name="eye_on_hand" value="false" />

        <arg name="tracking_base_frame" value="camera_link" />
        <arg name="tracking_marker_frame" value="camera_marker" />
        <arg name="robot_base_frame" value="base_link" />
        <arg name="robot_effector_frame" value="wrist_3_link" />

        <arg name="freehand_robot_movement" value="true" />
        <arg name="robot_velocity_scaling" value="0.5" />
        <arg name="robot_acceleration_scaling" value="0.2" />
    </include>

</launch>

Everything works fine but I have this problem:

![image](https://github.com/IFL-CAMP/easy_handeye/assets/116814244/4a82ff34-3d7a-43f3-bd05-68bbe7e57cbf)

I can't display the image /aruco_single/result

I think I have a problem with aruco_ros or with openni.

thank you in advance

**Comment by marcoesposito1988** [comment]
Hi @MARHEM602,

the error reported by Rviz means that the tf frame chosen by Rviz by default ("world") seems not to be present in your tf tree. This is not unusual. You have to select a different one in the Rviz global options, see here https://answers.ros.org/question/195962/rviz-fixed-frame-world-does-not-exist/
