### ISSUE TITLE
Failed to fetch current robot state

### ISSUE THREAD

**Issue by woshisj** [IFL-CAMP/easy_handeye#24]
when I check the staring pose in the rqt 
![image](https://user-images.githubusercontent.com/32431758/50483954-011b1600-0a29-11e9-9ecf-56407de724bf.png)
 some error appear   
Failed to fetch current robot state
![image](https://user-images.githubusercontent.com/32431758/50484059-843c6c00-0a29-11e9-97d1-6bcd2a89dc4c.png)

I am on Ubuntu 16.04 with ros kinetic and I am using a Kinova Jaco2 arm 
Is there any other place that I need to change the robotic arm file information?
and the launch file is

```
<!-- start the robot -->
<include file="$(find kinova_bringup)/launch/kinova_robot.launch">
</include>
<include file="$(find j2n6s300_moveit_config)/launch/j2n6s300_demo.launch">
</include>

<!-- start easy_handeye -->
<include file="$(find easy_handeye)/launch/calibrate.launch" >
    <arg name="namespace_prefix" value="$(arg namespace_prefix)" />
    <arg name="eye_on_hand" value="true" />

    <arg name="tracking_base_frame" value="pylon_camera" />
    <arg name="tracking_marker_frame" value="camera_marker" />
    <arg name="robot_base_frame" value="j2n6s300_link_base" />
    <arg name="robot_effector_frame" value="j2n6s300_end_effector" />

    <arg name="freehand_robot_movement" value="false" />
    <arg name="robot_velocity_scaling" value="0.5" />
    <arg name="robot_acceleration_scaling" value="0.2" />
</include>
```

**Comment by zhudelong** [comment]
Hi woshisj ,
@woshisj 
Have you solved your problem? How do you figure it out?
