### ISSUE TITLE
A small question about the AR Marker

### ISSUE THREAD

**Issue by EEYOYEE** [IFL-CAMP/easy_handeye#40]
I'm brandly new on the caibration. Before I run the demo,I want to know how the ar marker is made.
I have find the ArUco markers generator,but I don't know the dictionary and id.
Hope you can give me some information.
Thanks

**Comment by marcoesposito1988** [comment]
Hi @BeYoungs,

That is not necessary. You can print your marker with a standard inkjet printer.

What is important is that it is perfectly flat. You can glue it to a wooden or metal board, for example.

You must also double check the actual size of the marker after you print it (the printer might rescale the image automatically to fit it to the page).

**Comment by BeYoungs** [comment]
First I'm very thankful for you advice.
I have checked the real marker size and keep it flat when I doing the calibration.
However,after doing the calibration for several times, including the camera calibration and some links being checked,the x and z direction calibration data is very good. But there is almost 5cm error in the real distance between the camera and ur3.It results in the object-picking cannot move to the right place.
Could you give me some solutions to improve the calibration results of the y direction(the calibration data between the camera and ur3).
I used the camera of ASUS Xtion pro,should I use other camera for a try?like kinect?
Thanks again.

**Comment by marcoesposito1988** [comment]
Have you checked that the marker tracking is working correctly? This is a requirement for a good calibration.

You can check this without using the calibration, by moving the robot with the control panel, and comparing the Cartesian displacement of the end effector according to the robot panel and that of the marker according to the aruco marker. If you move the robot 5 cm up and the marker pose changes by 7 cm, you have a problem with the marker tracking (or a very big one with the robot, but that’s unlikely).

The hand-eye calibration uses external libraries for the computation, so if there is a problem it lies (usually) either in the configuration of the marker tracking, or in how you sample the data.
