### ISSUE TITLE
rqt_calibrationmovement GUI having issue with Handeye client 

### ISSUE THREAD

**Issue by waiyc** [IFL-CAMP/easy_handeye#49]
Hi,
I would like to try integrate handeye client functions into calibration movement gui. However, the GUI did not show up after I enable the `self.client = HandeyeClient()` line 25 in rqt_calibrationmovements.py`. Do you have any suggestions to overcome this problem?

**Comment by marcoesposito1988** [comment]
Hi @waiyc,

nothing comes to my mind. Could you give me a larger code sample?

**Comment by marcoesposito1988** [comment]
Closing for lack of feedback
