### ISSUE TITLE
Hello,I use your new code,I met this trouble:an empty 'ns'

### ISSUE THREAD

**Issue by lijialei666** [IFL-CAMP/easy_handeye#61]
![image](https://user-images.githubusercontent.com/33393975/95419981-34643600-096d-11eb-9bbb-48576314fb61.png)

**Comment by marcoesposito1988** [comment]
Thank you for reporting this!

Can you please try adding `<arg name="move_group_namespace" value="/">` to your inclusion of `calibrate.launch`?

If this works, I will set this as the default value.

**Comment by lijialei666** [comment]
the problem is resolved,but I met new problems.
![image](https://user-images.githubusercontent.com/33393975/95449516-7dc97b00-0997-11eb-8ece-19f7b5137430.png)
![image](https://user-images.githubusercontent.com/33393975/95449597-95a0ff00-0997-11eb-9a98-614dc5e728c2.png)
![image](https://user-images.githubusercontent.com/33393975/95449672-aa7d9280-0997-11eb-8fb4-8e98519f869e.png)

**Comment by lijialei666** [comment]
I need to solve this problem urgently. It has been bothering me for seven days,thank you very much.

**Comment by marcoesposito1988** [comment]
I would like to help you, but those problems look like they are not related to `easy_handeye` so I don't know if I can.

The first and third screenshot seem to point to a problem with your Qt installation. Does `rviz` start on your system?

The second says that `pyassimp` can't be imported by python, and it has a link to a known issue with MoveIt. I guess the solution should be there.

**Comment by lijialei666** [comment]
Thank you very much! I will try it.

**Comment by QRayMoor** [comment]
> Thank you very much! I will try it.

Hi there, I have the same problems you met. Have you solved it?
1. Where to add this `<arg name="move_group_namespace" value="/">` in `calibrate.launch`?
2. And how to solve the second screenshot problem ?

**Comment by lijialei666** [comment]
> > Thank you very much! I will try it.
> 
> Hi there, I have the same problems you met. Have you solved it?
> 
> 1. Where to add this `<arg name="move_group_namespace" value="/">` in `calibrate.launch`?
> 2. And how to solve the second screenshot problem ?

Hello, the first problem I have solved in calibrate.launch. The second problem I have not solved.

**Comment by marcoesposito1988** [comment]
Have you tried `sudo apt install python-pyassimp`?

**Comment by lijialei666** [comment]
> Have you tried `sudo apt install python-pyassimp`?

No, I have not tried it. But I've completed the calibration successfully by using old version easy_hand_eye.

**Comment by marcoesposito1988** [comment]
That's very interesting.. if that happens, then it should happen with both versions.

Which ROS distro are you using?

**Comment by lijialei666** [comment]
> That's very interesting.. if that happens, then it should happen with both versions.
> 
> Which ROS distro are you using?

Kinetic

**Comment by marcoesposito1988** [comment]
Ok, so it's definitely python 2.

I will try to reproduce the issue on my side

**Comment by lijialei666** [comment]
> I'm very sorry about this, I forgot to change back the shebang in the scripts. I just fixed this [now](https://github.com/IFL-CAMP/easy_handeye/commit/82576de5ddd302ee89592c2b5ea4073e91cdf288).
> 
> If you pull from the master branch, the new version should now work on all ROS distros.

Ok
