### ISSUE TITLE
i can't open rqt_easy_handeye/Hand-eye Calibration automatic movement ,hope your help

### ISSUE THREAD

**Issue by aoligeihahah** [IFL-CAMP/easy_handeye#62]
PluginManager._load_plugin() could not load plugin "rqt_easy_handeye/Hand-eye Calibration automatic movement":
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/plugin_handler.py", line 102, in load
    self._load()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/plugin_handler_direct.py", line 55, in _load
    self._plugin = self._plugin_provider.load(self._instance_id.plugin_id, self._context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 72, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 72, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_gui_py/ros_py_plugin_provider.py", line 60, in load
    return super(RosPyPluginProvider, self).load(plugin_id, plugin_context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 72, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_gui/ros_plugin_provider.py", line 101, in load
    return class_ref(plugin_context)
  File "/home/he/catkin_ws/src/easy_handeye/rqt_easy_handeye/src/rqt_easy_handeye/rqt_calibrationmovements.py", line 306, in __init__
    self._widget = CalibrationMovementsGUI()

**Comment by aoligeihahah** [comment]
![Uploading 2020-10-11 21-37-07屏幕截图.png…]()
![Uploading 2020-10-11 21-37-30屏幕截图.png…]()

**Comment by aoligeihahah** [comment]
![2020-10-11 21-37-07](https://user-images.githubusercontent.com/72695459/95680325-6a264a80-0c0b-11eb-99fd-e50a60affb13.png)
![2020-10-11 21-37-30](https://user-images.githubusercontent.com/72695459/95680327-6f839500-0c0b-11eb-83c3-5bedf547df65.png)

**Comment by marcoesposito1988** [comment]
I can't explain this behavior; I opened an [issue](https://github.com/ros-planning/moveit/issues/2364) in the MoveIt repo to ask for clarification.

This issue will happen in most cases, since usually the `move_group` action is located in the global namespace. As a workaround, you can include the launch file for your robot in a namespace, then pass that namespace as argument to `easy_handeye`:

```
<!-- note the ns="..." -->
<include ns="/my_robot" file="$(find ur10_moveit_config)/launch/..."/>

<!-- add the same namespace as move_group_namespace argument -->
<include file="$(find easy_handeye)/launch/calibrate.launch" >
...
        <arg name="move_group_namespace" value="/my_robot" />
...
</include>
```

**Comment by aoligeihahah** [comment]
Thank you for your help, but I'm showing this problem。
![2020-10-12 21-39-04](https://user-images.githubusercontent.com/72695459/95753152-c2c11a80-0cd3-11eb-84dc-5658de359e48.png)

**Comment by aoligeihahah** [comment]
I have added it as shown in the figure below.
![2020-10-12 21-40-48](https://user-images.githubusercontent.com/72695459/95753259-f1d78c00-0cd3-11eb-993f-e9b3260343d9.png)

**Comment by marcoesposito1988** [comment]
You are right, that workaround is not enough.

I should have managed to fix the problem in a way that doesn't require a workaround. I updated the code on the master branch; I hope this solves your problem. To test for this, I created a [version of the demo](https://github.com/marcoesposito1988/easy_handeye_demo/tree/master/launch/universal_robot) that uses the Universal Robot UR5.

**Comment by aoligeihahah** [comment]
Hello, I have updated the code, but I have some problems with the pictures. I hope you can help me
![2](https://user-images.githubusercontent.com/72695459/96464880-ec8dba80-125a-11eb-9b58-e573854b5272.png)
![3](https://user-images.githubusercontent.com/72695459/96464899-f1eb0500-125a-11eb-8cc7-8a3af5d20417.png)
![4](https://user-images.githubusercontent.com/72695459/96464913-f4e5f580-125a-11eb-860d-3ddd4cfde5bc.png)

**Comment by marcoesposito1988** [comment]
There is a problem with your system: it looks like PyQt5 is missing

**Comment by aoligeihahah** [comment]
![2020-11-01 16-48-29屏幕截图](https://user-images.githubusercontent.com/72695459/97798661-07046280-1c63-11eb-96f4-f44669ee9f36.png)
![2020-11-01 16-49-04屏幕截图](https://user-images.githubusercontent.com/72695459/97798666-0d92da00-1c63-11eb-8a79-eb40b5c916e1.png)
![2020-11-01 16-50-01屏幕截图](https://user-images.githubusercontent.com/72695459/97798672-14b9e800-1c63-11eb-9b75-d847b3408a29.png)
![2020-11-01 16-50-24屏幕截图](https://user-images.githubusercontent.com/72695459/97798675-1b485f80-1c63-11eb-9eda-f75d33d9439a.png)
![2020-11-01 16-50-35屏幕截图](https://user-images.githubusercontent.com/72695459/97798682-2b603f00-1c63-11eb-9496-4b11a9c398f1.png)
![2020-11-01 16-51-35屏幕截图](https://user-images.githubusercontent.com/72695459/97798685-31562000-1c63-11eb-9d66-538d857d51ff.png)

**Comment by aoligeihahah** [comment]
I have run successfully, but there is another problem
