### ISSUE TITLE
Can this package calibrate franka panda robot arm?

### ISSUE THREAD

**Issue by saprrow** [IFL-CAMP/easy_handeye#65]
As title, thank you!

**Comment by marcoesposito1988** [comment]
Hi @saprrow,

yes, it can calibrate any robot arm with MoveIt support.

I added an example to [easy_handeye_demo](https://github.com/marcoesposito1988/easy_handeye_demo/tree/master/launch/franka_panda), which you can take a look at to. You can just copy the launch files for the part regarding the robot. You will have to replace the tracking simulator with your actual tracking system.

**Comment by saprrow** [comment]
Okay! Thank you so much!

**Comment by saprrow** [comment]
> Hi @saprrow,
> 
> yes, it can calibrate any robot arm with MoveIt support.
> 
> I added an example to [easy_handeye_demo](https://github.com/marcoesposito1988/easy_handeye_demo/tree/master/launch/franka_panda), which you can take a look at to. You can just copy the launch files for the part regarding the robot. You will have to replace the tracking simulator with your actual tracking system.



> Hi @saprrow,
> 
> yes, it can calibrate any robot arm with MoveIt support.
> 
> I added an example to [easy_handeye_demo](https://github.com/marcoesposito1988/easy_handeye_demo/tree/master/launch/franka_panda), which you can take a look at to. You can just copy the launch files for the part regarding the robot. You will have to replace the tracking simulator with your actual tracking system.

Okay. Thank you so much!

**Comment by marcoesposito1988** [comment]
You're welcome! Happy calibrating!
