### ISSUE TITLE
Hello,I use your new code.The rqt_easy_handeye package indicates that many python modules are missing.

### ISSUE THREAD

**Issue by desstiony** [IFL-CAMP/easy_handeye#66]
Hello, after the compilation is successful, execute, the rqt_easy_handeye package prompts that many python modules are missing. How to solve the module problem at once

**Comment by marcoesposito1988** [comment]
Hi @desstiony,

did you do the `rosdep` step from the [Getting Started section](https://github.com/IFL-CAMP/easy_handeye#getting-started) of the README?

**Comment by desstiony** [comment]
thinks, I pulled and it works now.
