### ISSUE TITLE
is it possible to disable Moveit!

### ISSUE THREAD

**Issue by jackie-wayland** [IFL-CAMP/easy_handeye#73]
can we run this calibration without move_group?

**Comment by marcoesposito1988** [comment]
Hi @jackie-wayland,

yes, you can simply set the `freehand_robot_movement` argument of `calibrate.launch` to true (see [here](https://github.com/IFL-CAMP/easy_handeye/blob/master/easy_handeye/launch/calibrate.launch#L11)). 

But: you will still need the robot to publish its _updated_ pose into `tf` somehow. Please check that moving the robot makes the displayed position move in RViz before starting.

**Comment by jackie-wayland** [comment]
@marcoesposito1988 after set `freehand_robot_movement` as true, the `robot.py` still complain the `move_group` not found .

https://github.com/IFL-CAMP/easy_handeye/blob/e9ecd335202fb17030664479cb1e79807617c977/easy_handeye/launch/calibrate.launch#L48

Could you fix this?

**Comment by marcoesposito1988** [comment]
Sure, `robot.py` was introduced in a recent refactoring and I forgot to exclude it. Sorry about that.

What problem do you get with `rqt_easy_handeye` exactly?

**Comment by jackie-wayland** [comment]
@marcoesposito1988  the `rqt_easy_handeye` can't get the correct namespace.

**Comment by marcoesposito1988** [comment]
Was this the same problem as in #77? It should be solved by now then.

**Comment by jackie-wayland** [comment]
@marcoesposito1988  I will test it.
