### ISSUE TITLE
which kind of image should we use? raw_image or rect_image?

### ISSUE THREAD

**Issue by simba0703** [IFL-CAMP/easy_handeye#76]
We could get both the raw_image and rect_image for most cameras.Which one should we choose? Is there any difference?

**Comment by marcoesposito1988** [comment]
Hi @simba0703,

yes, you should definitely use `rect_image`. This image is computed from `raw_image` by applying the intrinsic camera calibration, which removes deformation artifacts and lets you know how far apart the points corresponding to two different pixels are, at a given depth (I am oversimplifying things to keep it brief; I encourage you to read more about the argument).

If you are just using an RGB camera, e.g. for marker tracking only, you will however definitely need to [perform the intrinsic calibration yourself](http://wiki.ros.org/camera_calibration/Tutorials/MonocularCalibration). 

If you are using an RGBD camera (kinect/realsense/orbbec/...), they usually are already calibrated by the manufacturer, and the ROS driver queries the intrinsic and stereo calibration through the camera SDK.
