### ISSUE TITLE
Stuck at loading parameters

### ISSUE THREAD

**Issue by AlexSunNik** [IFL-CAMP/easy_handeye#77]
I disabled the MoveIt(because we control the robot with another interface) and RViz(already have a configured RViz window opened by myself) but checked beforehand that all the required tf frames, robot_base, end_effector, camera_link, and marker will be provided and updated properly. However, when running the launch file, I'm stuck at:
[INFO] [1610429294.391226]: Loading parameters for calibration /my_eob_calib_eye_on_base/ from the parameters server

Any idea why?
Thanks again for the amazing work and help.

**Comment by AlexSunNik** [comment]
Problem Solved. You should do the motion part of the function `set_namespace()` in `handeye_client.py` based on the `freehand_robot_movement` argument. After I make the changes, I'm able to do the calibration now. The result computed seems reasonable by just visualizing it in Rviz. Thanks again for the amazing work.

**Comment by marcoesposito1988** [comment]
I see.. thanks for the bug report!

**Comment by marcoesposito1988** [comment]
This should be now fixed with version 0.4.2
