### ISSUE TITLE
Unable to see calibration GUI

### ISSUE THREAD

**Issue by Yitian-Xian** [IFL-CAMP/easy_handeye#88]
Hi all, I am using this package on melodic + ROS + Ubuntu 18.04 + UR5 robot.

As suggested by others, I have three launch file: the first one is responsible for opening the kinect: `roslaunch kinect2_bridge kinect2_bridge.launch`.

The second one opens the aruco marker package and ur5 driver(also the moveit planning things): `roslaunch easy_handeye ur5_kinectv2_calibration.launch`. the file can be seen as follows:

![cut1](https://user-images.githubusercontent.com/60846461/122156590-d98bc280-ce9b-11eb-9c69-6fd8069711e1.png)

The third one opens the calibration program and the rviz GUI: `roslaunch easy_handeye easy.launch`. It looks like:

![cut2](https://user-images.githubusercontent.com/60846461/122156680-0f30ab80-ce9c-11eb-930b-a5c4f7fbf167.png)

However, the result is very strange. One program just shows empty and the other one seems good. I have attached the photo below.

![cut](https://user-images.githubusercontent.com/60846461/122155724-28385d00-ce9a-11eb-8da8-689100748652.png)

Can anyone help me with this problem? Thank you!!!

**Comment by Yitian-Xian** [comment]
By the way, this was nothing wrong in the command terminal when I ran the third command, so I do not have any idea how to debug...

**Comment by marcoesposito1988** [comment]
Hi @Yitian-Xian,

this is weird, I don't manage to replicate it.

Can you please try out [easy_handeye_demo](https://github.com/marcoesposito1988/easy_handeye_demo), to exclude that the problem is related to the hardware configuration or to your launch files?

**Comment by OwenKZ** [comment]
I face the same question. And I am using kinova gen3-lite and realsense d435i. I have no idea why the rqt_easy_handeye program is empty. 
Can you please tell me how to fix it if you have already solved this problem?

**Comment by YoanDev** [comment]
I solve this issue.
It's very strange, I went in the directory of scripts in rqt_easy_handeye and I launch the python file rqt_easy_handeye.
The python file doesn't work but, after, you can launch rviz and the GUI will be not empty.

**Comment by marcoesposito1988** [comment]
This seems to be due to stale rqt configuration. Please reopen if the issue happens again after using the proposed solution (`rosrun rqt_gui rqt_gui --clear-config`)
