### ISSUE TITLE
Rotation parameters are overwriting the translation parameters

### ISSUE THREAD

**Issue by ravijo** [IFL-CAMP/easy_handeye#89]
Thank you very much for creating this package. Please see the below lines

https://github.com/IFL-CAMP/easy_handeye/blob/0c2e44eecd2ad89a2f752434020de1115d79704e/easy_handeye/src/easy_handeye/handeye_calibration.py#L213-L220

The rotation parameters are overwriting the translation parameters. The rotation parameters must be written with the `q` prefix as shown below:

```
rospy.set_param(namespace + 'transformation/qx', t.rotation.x)
rospy.set_param(namespace + 'transformation/qy', t.rotation.y)
rospy.set_param(namespace + 'transformation/qz', t.rotation.z)
rospy.set_param(namespace + 'transformation/qw', t.rotation.w)
```

**Comment by marcoesposito1988** [comment]
Excellent catch, thank you @ravijo!
