### ISSUE TITLE
eye-in-hand example ?

### ISSUE THREAD

**Issue by Abduoit** [IFL-CAMP/easy_handeye#9]
Hi

How to run the eye-in-hand example, using normal webcam

should I bring up the real hand first, then run `calibrate.launch `

or create a file with following details and launch it 

```
<launch>
  <include file="$(find easy_handeye)/launch/calibrate.launch">
    <arg name="eye_on_hand" value="true"/>

    <arg name="robot_base_frame" value="/base_link"/>
    <arg name="robot_effector_frame" value="/ee_link"/>

    <arg name="tracking_base_frame" value="/optical_origin"/>
    <arg name="tracking_marker_frame" value="/optical_target"/>
  </include>
</launch>
```

**Comment by marcoesposito1988** [comment]
Sorry, I just noticed that somehow this issue slipped my attention completely.

For future reference: you can create a single launch file that starts the robot driver, the camera, and the easy_handeye calibration. The latter should be robust to the startup order.
