### ISSUE TITLE
Realsense example

### ISSUE THREAD

**Issue by lalazari** [IFL-CAMP/easy_handeye#92]
Hello,
Thanks for your excellent work.

Is there any chance to provide the launch file for intel's realsense modules?

Thanks again,
L.L

**Comment by lyh458** [comment]
Hi @lalazari, maybe this repo [ur5_realsense_calibration](https://github.com/portgasray/ur5_realsense_calibration) can help you.

**Comment by lalazari** [comment]
Hi @lyh458, thanks for your reply. I will check it asap.

**Comment by marcoesposito1988** [comment]
@lalazari you can find an example here https://github.com/IFL-CAMP/easy_handeye/blob/master/docs/example_launch/panda_realsense_eyeonbase.launch
