### ISSUE TITLE
What should I do to use with Xarm6

### ISSUE THREAD

**Issue by Aki92-Xavier** [IFL-CAMP/easy_handeye#96]
Hi,I am trying to use easy_handeye with realsense D435 and Xarm6.
Do you have any suggestion.

**Comment by marcoesposito1988** [comment]
As suggested by the documentation, you should use the official ROS Moveit config provided by the robot producer to connect to the robot. For the realsense camera, you can also find examples in the easy_handeye docs, for example https://github.com/IFL-CAMP/easy_handeye/blob/master/docs/example_launch/panda_realsense_eyeonbase.launch

**Comment by Akumar201** [comment]
Hello, I would like to know in the above example how can I use other camera than realsense ? I want to use simple camera such that data transmission can be efficient even after using long wire.
