### ISSUE TITLE
can‘t open Hand-eye Calibration automatic movement

### ISSUE THREAD

**Issue by Minpig** [IFL-CAMP/easy_handeye#98]
Hand-eye Calibration automatic movement

the other two interfaces can be opened，only the interface about “Hand-eye Calibration automatic movement” cannot be opened，why？my environment is：ubuntu16.04, ros-kinetic，python2.7，opencv2.4.9，robot:ufactory_xarm6, camera:realsense D435i. Do I want to upgrade to Ubuntu 18.0 04 or upgrade opencv version?
 
![2022-05-04 08-43-42屏幕截图](https://user-images.githubusercontent.com/40198654/166609201-2efa6453-db23-4ac8-82a5-bac445306cc2.png)

![2022-05-04 08-53-31屏幕截图](https://user-images.githubusercontent.com/40198654/166609849-f8551029-a2d9-439d-8728-530bfcf45cdb.png)

![2022-05-04 08-53-48屏幕截图](https://user-images.githubusercontent.com/40198654/166609854-2fa29c0f-65b8-4062-bfcb-c831472d42cd.png)

![2022-05-04 16-06-33屏幕截图](https://user-images.githubusercontent.com/40198654/166643835-2fb46b02-9129-4af9-b702-e526d1ebab8a.png)

![2022-05-04 16-06-13屏幕截图](https://user-images.githubusercontent.com/40198654/166643848-073acfe0-2620-4740-82ca-1c843f2a9b1f.png)

**Comment by Minpig** [comment]
I tried to install opencv4.2.0 with the source code,.After installation, I found that  “Hand-eye Calibration automatic movement”  still didn't appear

**Comment by Minpig** [comment]
iIhad solved.

**Comment by Akumar201** [comment]
Hello, I am using the same arm and getting the same error, can you please help me solving this ?
![image](https://user-images.githubusercontent.com/108360879/192834158-0dc546e8-9c9f-4685-8c3a-8db3a003802f.png)
<launch>
    <arg name="namespace_prefix" default="xarm_realsense_handeyecalibration" />
    <arg name="robot_ip" doc="The IP address of the xarm robot" />
    <arg name="robot_dof" doc="The degree of freedom of the xarm" />
    
    <arg name="marker_size" doc="Size of the ArUco marker used, in meters" default="0.1" />
    <arg name="marker_id" doc="The ID of the ArUco marker used" default="105"/>

    
    <include file="$(find realsense2_camera)/launch/rs_camera.launch" />

    
    <node name="aruco_tracker" pkg="aruco_ros" type="single">
        <remap from="/camera_info" to="/camera/color/camera_info" />
        <remap from="/image" to="/camera/color/image_raw" />
        <param name="image_is_rectified" value="true"/> 
        <param name="marker_size"        value="$(arg marker_size)"/>
        <param name="marker_id"          value="$(arg marker_id)"/>
        <param name="reference_frame"    value="camera_color_optical_frame"/>
        <param name="camera_frame"       value="camera_color_optical_frame"/>
        <param name="marker_frame"       value="camera_marker" />
    </node>

    
    <include if="$(eval arg('robot_dof')==7)" file="$(find xarm7_moveit_config)/launch/realMove_exec.launch">
        <arg name="robot_ip" value="$(arg robot_ip)" />
        <arg name="show_rviz" value="false" />
    </include>
    <include if="$(eval arg('robot_dof')==6)" file="$(find xarm6_moveit_config)/launch/realMove_exec.launch">
        <arg name="robot_ip" value="$(arg robot_ip)" />
        <arg name="show_rviz" value="false" />
    </include>
    <include if="$(eval arg('robot_dof')==5)" file="$(find xarm5_moveit_config)/launch/realMove_exec.launch">
        <arg name="robot_ip" value="$(arg robot_ip)" />
        <arg name="show_rviz" value="false" />
    </include>

    
    <include file="$(find easy_handeye)/launch/calibrate.launch" >
        <arg name="namespace_prefix" value="$(arg namespace_prefix)" />
                
        <arg name="eye_on_hand" value="true" />
        <arg name="tracking_base_frame" value="camera_color_optical_frame" />
        <arg name="tracking_marker_frame" value="camera_marker" />
        <arg name="robot_base_frame" value="link_base" />
        <arg name="robot_effector_frame" value="link_eef" />

        <arg name="freehand_robot_movement" value="false" />
        <arg name="robot_velocity_scaling" value="0.1" />
        <arg name="robot_acceleration_scaling" value="0.1" />
        <arg name="move_group" value="xarm$(arg robot_dof)" />
    </include>
    
    <node name="recognition_view" pkg="image_view" type="image_view" args="image:=/aruco_tracker/result" />
</launch>

**Comment by Minpig** [comment]
I didn't encounter this problem. I'm sorry I can't help you




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月29日(星期四) 凌晨0:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [IFL-CAMP/easy_handeye] can‘t open Hand-eye Calibration automatic movement (Issue #98)





 
Hello, I am using the same arm and getting the same error, can you please help me solving this ?
 
 
 
 
 
 
 
 
 <!-- start the Realsense435 --&gt; <include file="$(find realsense2_camera)/launch/rs_camera.launch" /&gt; <!-- start ArUco --&gt; <node name="aruco_tracker" pkg="aruco_ros" type="single"&gt;     <remap from="/camera_info" to="/camera/color/camera_info" /&gt;     <remap from="/image" to="/camera/color/image_raw" /&gt;     <param name="image_is_rectified" value="true"/&gt; <!-- no distortion? --&gt;     <param name="marker_size"        value="$(arg marker_size)"/&gt;     <param name="marker_id"          value="$(arg marker_id)"/&gt;     <param name="reference_frame"    value="camera_color_optical_frame"/&gt;     <param name="camera_frame"       value="camera_color_optical_frame"/&gt;     <param name="marker_frame"       value="camera_marker" /&gt; </node&gt; <!-- start the robot --&gt; <include if="$(eval arg('robot_dof')==7)" file="$(find xarm7_moveit_config)/launch/realMove_exec.launch"&gt;     <arg name="robot_ip" value="$(arg robot_ip)" /&gt;     <arg name="show_rviz" value="false" /&gt; </include&gt; <include if="$(eval arg('robot_dof')==6)" file="$(find xarm6_moveit_config)/launch/realMove_exec.launch"&gt;     <arg name="robot_ip" value="$(arg robot_ip)" /&gt;     <arg name="show_rviz" value="false" /&gt; </include&gt; <include if="$(eval arg('robot_dof')==5)" file="$(find xarm5_moveit_config)/launch/realMove_exec.launch"&gt;     <arg name="robot_ip" value="$(arg robot_ip)" /&gt;     <arg name="show_rviz" value="false" /&gt; </include&gt; <!-- start easy_handeye --&gt; <include file="$(find easy_handeye)/launch/calibrate.launch" &gt;     <arg name="namespace_prefix" value="$(arg namespace_prefix)" /&gt;     <!-- eye on hand: true --&gt;             <arg name="eye_on_hand" value="true" /&gt;     <arg name="tracking_base_frame" value="camera_color_optical_frame" /&gt;     <arg name="tracking_marker_frame" value="camera_marker" /&gt;     <arg name="robot_base_frame" value="link_base" /&gt;     <arg name="robot_effector_frame" value="link_eef" /&gt;     <arg name="freehand_robot_movement" value="false" /&gt;     <arg name="robot_velocity_scaling" value="0.1" /&gt;     <arg name="robot_acceleration_scaling" value="0.1" /&gt;     <arg name="move_group" value="xarm$(arg robot_dof)" /&gt; </include&gt; <!-- in case rqt_easy_handeye image viewer fails to open: --&gt; <node name="recognition_view" pkg="image_view" type="image_view" args="image:=/aruco_tracker/result" /&gt;

**Comment by Akumar201** [comment]
Thank you for your response, I have done the calibration, can you please suggest me how can I cross check that my calibration results are good. Looking forward to hearing back from you. Thank you in advance.

**Comment by marcoesposito1988** [comment]
You can use the tf visualization to inspect the quality of the calibration. If it is correct, while moving the robot around you should see that the position of the tf frames in the world is plausible. Otherwise they will fly around (as it happens during the calibration process)
